# [START runtime] https://github.com/facebook/create-react-app/issues/2077
runtime: nodejs10
service: default
env: standard
instance_class: F1
# [END runtime]

# [START handlers]
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
# [END handlers]
