# [START runtime] https://github.com/facebook/create-react-app/issues/2077
runtime: nodejs10
service: default
env: standard
instance_class: F1
# [END runtime]

# [START handlers]
handlers:
  - url: /
    static_files: src/main/webapp/index.html
    upload: src/main/webapp/index.html

  - url: /(.*)
    static_files: src/main/webapp/\1
    upload: src/main/webapp/(.*)

  - url: /campaign
    script: auto
    login: optional
    secure: optional
# [END handlers]
